name: Run Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unit tests
      run: |
        python -m pytest -m unit

    - name: Integration tests
      run: |
        python -m pytest -m integration